name: Deploy Antrian SPMB Web

on:
  push:
    branches:
      - main
      - master # Menambahkan master untuk berjaga-jaga jika branch utamanya bernama master

jobs:
  web-deploy:
    name: 🎉 Membangun dan Upload App
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Mengambil Kode dari GitHub
      uses: actions/checkout@v4

    - name: ⚙️ Persiapan Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 📦 Mengunduh Modul (NPM Install)
      run: npm install

    - name: 🏗️ Memulai Kompilasi (NPM Run Build)
      run: npm run build
      env:
        # Variabel publik disematkan langsung agar aplikasi mendapatkan URL Supabase
        VITE_SUPABASE_URL: "https://izgudhyhstsxuokqvwoo.supabase.co"
        VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Z3VkaHloc3RzeHVva3F2d29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwNTcxMzYsImV4cCI6MjA5MTYzMzEzNn0.GCxCr284wto4j8nDevlOoz2wEsu2toH-ZjUbtM-8Lx0"

    - name: 🚀 Mengirim ke Web Hosting via Jalur FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ./
